---
- name: Install server sonar
  hosts: serversonar
  become: true

#  vars:
#    # Latest version of SonarQube, from http://www.sonarqube.org/downloads/
#    sonar_version: 5.6.1

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Ubuntu'
      changed_when: false

    - name: Install dependencies.
      package:
        name:
          - curl
          - unzip
        state: present

  roles:
    - role: java
    - role: postgresql
    - role: sonar

  post_tasks:
    - name: Ensure SonarQube is running.
      uri:
        url: "http://127.0.0.1:9000/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
