---
- name: Include version-specific variables for Ubuntu.
  include_vars: "Ubuntu-18.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Define java_packages.
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

# Setup/install tasks.
- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: ../templates/java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home
