---
workspace: /root
sonar_download_validate_certs: true

# ansible_os_family
ansible_os_family: Ubuntu

user_pass_hash: "$6$xyz$Q4Wq6GOKt2WdCprXdq/K//V7K94xXAT9gNMU0Aj3EAothvBoLVyIx8eANhEc.kec7/y7YhuEB98YVkEp4vV561" #sonar

# Default to the latest LTS release.
sonar_version: 7.9.2
sonar_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonar_version }}.zip"
sonar_version_directory: "sonarqube-{{ sonar_version }}"

sonar_web_context: ''

# Postgresql database connection details.
sonar_postgresql_username: sonar
sonar_postgresql_password: sonar

sonar_postgresql_host: localhost
sonar_postgresql_port: "5432"
sonar_postgresql_database: sonar

sonar_postgresql_allowed_hosts:
  - "127.0.0.1"
  - "::1"
  - "localhost"
